services:
  backend:                   # Servicio para el backend
    build: ./backend         # Construye usando el Dockerfile del backend
    ports:
      - "3000:3000"          # Abre el puerto 3000 (afuera e internamente)
    environment:            # Variables de entorno que puedes usar
      - NODE_ENV=production
      - DB_HOST=db           # Asegúrate de que el backend se conecte al contenedor de la base de datos
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb
    depends_on:
      - db                   # Espera a que la base de datos esté lista
    entrypoint: ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]  # Usa un script para esperar a MySQL

  frontend:                  # Servicio para el frontend
    build: ./frontend        # Construye usando el Dockerfile del frontend
    ports:
      - "8080:80"            # Abre el puerto 8080 en tu PC (80 adentro)

  db:                        # Servicio para MySQL
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"          # Abre el puerto de MySQL
    volumes:
      - db-data:/var/lib/mysql  # Persistencia de la base de datos

volumes:
  db-data:                  # Volumen para la base de datos (para persistir datos)
